# Generated by Django 4.1.3 on 2023-01-15 10:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام ویدئو')),
                ('video', models.FileField(upload_to='')),
                ('info', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('Author', models.CharField(choices=[('AmirMasoud Kheradmandi', 'AmirMasoud Kheradmandi'), ('Erfan Karimi', 'Erfan Karimi')], default='AmirMasoud Kheradmandi', max_length=100)),
                ('level', models.CharField(choices=[('پیشرفته', 'پیشرفته'), ('مقدماتی', 'مقدماتی'), ('متوسط', 'متوسط')], default='متوسط', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.category')),
            ],
        ),
    ]
