# Generated by Django 4.1.3 on 2023-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
