# Generated by Django 4.1.3 on 2023-01-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
