# Generated by Django 4.1.3 on 2023-01-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_comment_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('دوره در حال ظبط', 'دوره در حال ظبط'), ('ظبط دوره به پایان رسیده است', 'ظبط دوره به پایان رسیده است')], default='دوره در حال ظبط', max_length=150),
        ),
    ]
