# Generated by Django 4.1.3 on 2023-01-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('در حال ظبط', 'در حال ظبط'), ('پایان ظبط', 'پایان ظبط')], default='در حال ظبط', max_length=150),
        ),
    ]
