# Generated by Django 4.1.3 on 2023-01-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='telegram',
        ),
        migrations.AddField(
            model_name='footer',
            name='telegram1',
            field=models.CharField(max_length=150, null=True, verbose_name='Masoud Telegram'),
        ),
        migrations.AddField(
            model_name='footer',
            name='telegram2',
            field=models.CharField(max_length=150, null=True, verbose_name='Erfan Telegram'),
        ),
    ]
