# Generated by Django 4.1.3 on 2023-01-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_footer_telegram_footer_telegram1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوبار')),
                ('link', models.CharField(max_length=100, verbose_name='لینک نوبار')),
            ],
        ),
        migrations.CreateModel(
            name='NavTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوبار')),
                ('link', models.CharField(max_length=100, verbose_name='لینک نوبار')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.navone')),
            ],
        ),
    ]
