# Generated by Django 4.1.3 on 2023-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_navone_navtwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navone',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک نوبار'),
        ),
    ]
